FROM ubuntu:trusty

RUN apt-get update \
        && apt-get install -y --no-install-recommends \
                gcc-mingw-w64-x86-64 \
                make \
                autoconf \
                gperf \
                zlib1g-dev \
        && rm -rf /var/lib/apt/lists/*

WORKDIR /tmp/build

COPY . .

ENV CC x86_64-w64-mingw32-gcc

RUN ./autogen.sh \
        && ./configure --host=x86_64-w64-mingw32 \
        && make \
        && make test/main.exe

